# Enable Kodiak
version = 1

[merge]
# Required label
# Forces label requirements
require_automerge_label = true

# Labels for Automerge
# This Label is shared with Luna.
#-----------------------------------
# Conflicts are avoided by explicitly blacklisting Actor:Luna label
# Luna handles this gracefullym by first adding this label before doing
# any other tasks. If adding Actor:Luna label fails, Luna will not act
# on that PR/Issue.
automerge_label = "Luna:AutoMerge"

# Methods
method = "squash"

# Blacklisted Labels
# Actor:Luna                  - Prevent conflicts with Luna
# Status:WIP, Status:Blocked  - Prevent merging WIP or blocked PRs
# Status:Stale, Status:Locked - Prevent merging stale PRs
blocking_labels = ["Status:WIP", "Status:Locked", "Actor:Luna", "Status:Blocked", "Status:Stale"]

# Priority
priority_merge_label = "Priority:Critical"

# Cleanup stale branches
delete_branch_on_merge = true

# On conflicts, remove automerge labels
notify_on_conflict = true

# Wait to Pass checks
optimistic_updates = false

[merge.message]
body = "pull_request_body"
strip_html_comments = true
body_type = "markdown"
cut_body_before = "<!-- COMMIT-NOTES-BEGIN -->"
cut_body_after = "<!-- COMMIT-NOTES-END-->"


[merge.automerge_dependencies]
# only auto merge "minor" and "patch" version upgrades.
# do not automerge "major" version upgrades.
versions = ["patch"]
usernames = ["dependabot"]


[update]
require_automerge_label = false

# Auto update label is sharedwith Luna
autoupdate_label = "Luna:AutoUpdate"

# Ignore bots or other apps with automerge built in and kodiak should ignore then
ignored_usernames = ["valarie-ci-bot", "dependabot-preview", "luna-bot"]

# diana:{diana_urn_flavor}:{remote}:{source}:{version}:{remote_path}:{type}
# diana:2:github:tprasadtp/templates::bots/kodiak.toml:static
