# domain
baseurl: "/virtio-whql"
url: "https://tprasadtp.github.io"

# meta
title: VirtIO WHQL Drivers from CentOS
description: WHQL Drivers for virtio devices from CentOS 8 project, Signed by Microsoft/
show_downloads: false
remote_theme: pmarsceill/just-the-docs
# Logo
logo: "https://static.prasadt.com/logos/projects/artemis/scalable/sysadmin.svg"
# Enable Search
search_enabled: true

# Misc
permalink: pretty
color_scheme: dark


# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/tprasadtp/virtio-whql/"

# Makes Aux links open in a new tab
aux_links_new_tab: true
