name: build
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Upload ISO
        uses: actions/upload-artifact@v2
        with:
          name: virtio-win.iso
          path: docker/build/virtio-win.iso
          retention-days: 7

      - name: Upload VERSION.txt
        uses: actions/upload-artifact@v2
        with:
          name: VERSION.txt
          path: docker/build/VERSION.txt
          retention-days: 7

      - name: Files
        run: |
          ls -alh docker/build/
          cat docker/build/VERSION.txt

  # Verify using bundled signtool
  verify:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    needs:
      - extract
    steps:
      - uses: actions/checkout@v2

      - name: Download ISO
        uses: actions/download-artifact@v2
        with:
          name: virtio-win.iso

      - name: Mount ISO
        run: |
          Write-Host "Mounting ISO Image"
          Mount-DiskImage -StorageType ISO -ImagePath ${env:GITHUB_WORKSPACE}\virtio-win.iso
          Get-DiskImage ${env:GITHUB_WORKSPACE}\virtio-win.iso | Get-Volume

      - name: Get Mountpoint
        run: |
          Write-Host "Export Drive Letter"
          $IsoMountDriveLetter = (Get-DiskImage ${env:GITHUB_WORKSPACE}\virtio-win.iso | Get-Volume).DriveLetter
          echo "ISO_MOUNTPOINT=$IsoMountDriveLetter" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Verify ballon driver
        run: tools\signtool.exe verify /pa /v /c ${env:ISO_MOUNTPOINT}:\Balloon\w10\amd64\balloon.cat ${env:ISO_MOUNTPOINT}:\Balloon\w10\amd64\balloon.sys

      - name: Verify vioscsi driver
        run: tools\signtool.exe verify /pa /v /c ${env:ISO_MOUNTPOINT}:\vioscsi\w10\amd64\vioscsi.cat ${env:ISO_MOUNTPOINT}:\vioscsi\w10\amd64\vioscsi.sys

  # Release if
  # 1. Latest tag on GitHub differs from extracted version
  # 2. If on master branch
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    needs:
      - extract
      - verify
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download ISO
        uses: actions/download-artifact@v2
        with:
          path: docker/build/
          name: virtio-win.iso

      - name: Download VERSION.txt
        uses: actions/download-artifact@v2
        with:
          path: docker/build/
          name: VERSION.txt

      - name: Mount and Extract
        run: |
          echo "Mount ISO"
          sudo mkdir /mnt/virtio-iso
          sudo chown $USER:$USER /mnt/virtio-iso
          sudo chmod 755 /mnt/virtio-iso
          echo "Mounting ISO"
          sudo mount -o loop docker/build/virtio-win.iso /mnt/virtio-iso
          echo "Copy Installers"
          cp /mnt/virtio-iso/virtio-win-guest-tools.exe docker/build/virtio-win-guest-tools.exe
          cp /mnt/virtio-iso/virtio-win-gt-x64.msi docker/build/virtio-win-gt-x64.msi



      - name: Install git-chglog
        run: |
          brew tap git-chglog/git-chglog
          brew install git-chglog

      - name: Release if necessary
        run: |
          ls -alh docker/build
          ./tools/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
