name: build
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
jobs:
  # ISO
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        run: make build

      - name: Install git-chglog
        run: |
          brew tap git-chglog/git-chglog
          brew install git-chglog

      - name: Generate Changelog
        run: |
          make changelog
          cat docs/changelog.md

      - name: Upload ISO
        uses: actions/upload-artifact@v2
        with:
          name: virtio-win.iso
          path: docker/build/virtio-win.iso
          retention-days: 7

  verify:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    needs:
      - extract
    steps:
      - name: Download ISO
        uses: actions/download-artifact@v2
        with:
          name: virtio-win.iso

      - name: Mount ISO
        run: |
          Write-Host "Mounting ISO Image"
          Mount-DiskImage -StorageType ISO -ImagePath virtio-win.iso
          Get-DiskImage virtio-win.iso | Get-Volume

      - name: Verify Ballon Driver
        run:
          Signtool verify /pa /v /c D:\Balloon\w10\amd64\balloon.cat D:\Balloon\w10\amd64\balloon.sys
        continue-on-error: true

      - name: Verify VIOSCSI Driver
        run:
          Signtool verify /pa /v /c D:\vioscsi\w10\amd64\vioscsi.cat D:\Balloon\w10\amd64\vioscsi.sys
        continue-on-error: true
